server:
  port: 8080
  servlet:
    #session最大超时时间（分钟），默认30分钟
    session:
      timeout: 60
  #tomcat的URL编码
  tomcat:
    uri-encoding: UTF-8
  #需要的时候再配置
#  address: 192.168.43.128
spring:
  datasource:
    name: xpu
    url: jdbc:mysql://localhost:3306/xpu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1235
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false  #设置开启热部署
      additional-paths: src/main/java #重启目录
      #排除那个目录下的文件不需要restart
#      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效


#整合mybatis
mybatis:
  type-aliases-package: com.okgo.goodhelper.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml







